/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.Calc;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpringLayout;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author comp9
 */
public class EntradaDados extends javax.swing.JInternalFrame {

    /**
     * Creates new form EntradaDados
     */
    double x, y, r, ang, vel, dir;
    double[] result = new double[2];
    Calc cal = new Calc();
    TelaPrincipal frame;
    DefaultTableModel model;

    public EntradaDados(DefaultTableModel t, TelaPrincipal f) {
        this.model = t;
        this.frame = f;
        initComponents();

    }

    /* public EntradaDados(TelaPrincipal f) {
        this.frame = f;
        initComponents();
    }*/
    public EntradaDados() {
        initComponents();
    }

    public void setarCampos() {

        textAngulo.setText("");
        textDirecao.setText("");
        textRaio.setText("");
        textVelocidade.setText("");
        textX.setText("");
        textY.setText("");
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        botaoCartesiana = new javax.swing.JRadioButton();
        labelX = new javax.swing.JLabel();
        textX = new javax.swing.JTextField();
        labelY = new javax.swing.JLabel();
        textY = new javax.swing.JTextField();
        labelRaio = new javax.swing.JLabel();
        botaoPolar = new javax.swing.JRadioButton();
        textRaio = new javax.swing.JTextField();
        labelAngulo = new javax.swing.JLabel();
        textAngulo = new javax.swing.JTextField();
        botaoInserir = new javax.swing.JButton();
        labelVelocidade = new javax.swing.JLabel();
        labelDirecao = new javax.swing.JLabel();
        textVelocidade = new javax.swing.JTextField();
        textDirecao = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Entrada de Dados");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Coordenada"));

        botaoCartesiana.setText("Cartesiana");
        botaoCartesiana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCartesianaActionPerformed(evt);
            }
        });

        labelX.setText("X:");

        textX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textXFocusLost(evt);
            }
        });
        textX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textXMouseExited(evt);
            }
        });

        labelY.setText("Y:");

        textY.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textYFocusLost(evt);
            }
        });

        labelRaio.setText("Raio:");

        botaoPolar.setText("Polar");
        botaoPolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPolarActionPerformed(evt);
            }
        });

        textRaio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textRaioFocusLost(evt);
            }
        });

        labelAngulo.setText("Ângulo:");

        textAngulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textAnguloFocusLost(evt);
            }
        });

        botaoInserir.setText("Inserir");
        botaoInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInserirActionPerformed(evt);
            }
        });

        labelVelocidade.setText("Velocidade:");

        labelDirecao.setText("Direção:");

        textDirecao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textDirecaoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(labelY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textY))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(labelX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textX, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelAngulo)
                            .addComponent(labelRaio)))
                    .addComponent(botaoCartesiana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(botaoPolar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textAngulo, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(textRaio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelVelocidade)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(labelDirecao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textDirecao, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(textVelocidade))))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(botaoInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPolar)
                    .addComponent(botaoCartesiana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelX)
                            .addComponent(textX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRaio)
                            .addComponent(textRaio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelY)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelAngulo)
                                .addComponent(textAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelVelocidade)
                            .addComponent(textVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textDirecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDirecao))))
                .addGap(29, 29, 29)
                .addComponent(botaoInserir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCartesianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCartesianaActionPerformed
        // TODO add your handling code here:
        textX.setEnabled(true);
        textY.setEnabled(true);
        textRaio.setEnabled(false);
        textAngulo.setEnabled(false);
    }//GEN-LAST:event_botaoCartesianaActionPerformed

    private void textYFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textYFocusLost
        // TODO add your handling code here:
        try {
            if (textX.getText().isEmpty()) {
                textX.setText("0");
            }
            x = verificaDouble(textX.getText().replaceAll(",", "."));
            y = verificaDouble(textY.getText().replaceAll(",", "."));

            result = cal.transformaPolar(x, y);
            textRaio.setText(String.valueOf(new DecimalFormat("#.00").format(result[0])));
            textAngulo.setText(String.valueOf(new DecimalFormat("#.00").format(result[1])));
            r = result[0];
            ang = result[1];
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_textYFocusLost

    private void botaoPolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPolarActionPerformed
        // TODO add your handling code here:
        textX.setEnabled(false);
        textY.setEnabled(false);
        textRaio.setEnabled(true);
        textAngulo.setEnabled(true);
    }//GEN-LAST:event_botaoPolarActionPerformed

    private void textAnguloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textAnguloFocusLost
        // TODO add your handling code here:
        try {

            if (textRaio.getText().isEmpty()) {
                textRaio.setText("0");
            }

            r = verificaDouble(textRaio.getText().replaceAll(",", "."));
            ang = verificaDouble(textAngulo.getText().replaceAll(",", "."));

            result = cal.transformaCartesiano(r, ang);
            textX.setText(String.valueOf(new DecimalFormat("#.00").format(result[0])));
            textY.setText(String.valueOf(new DecimalFormat("#.00").format(result[1])));

            x = result[0];
            y = result[1];
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_textAnguloFocusLost

    private void botaoInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInserirActionPerformed
        // TODO add your handling code here:
        frame.iniciaThread();
        try {
            vel = verificaDouble(textVelocidade.getText().replaceAll(",", "."));
            dir = verificaDouble(textDirecao.getText().replaceAll(",", "."));
            Object data[] = new Object[]{false, model.getRowCount(),
                String.valueOf(new DecimalFormat("#.00").format(x)), String.valueOf(new DecimalFormat("#.00").format(y)),
                String.valueOf(new DecimalFormat("#.00").format(r)), String.valueOf(new DecimalFormat("#.00").format(ang)),
                String.valueOf(new DecimalFormat("#.00").format(vel)), String.valueOf(new DecimalFormat("#.00").format(dir))};
            //System.out.println("" + model.getRowCount());
            frame.insereTabela(data);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoInserirActionPerformed


    private void textDirecaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDirecaoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_textDirecaoFocusLost

    private void textXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textXMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_textXMouseExited

    private void textXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textXFocusLost

        try {
            x = verificaDouble(textX.getText().replaceAll(",", "."));

            if (textY.getText().isEmpty()) {
                textY.setText("0");
            }
            y = verificaDouble(textY.getText().replaceAll(",", "."));

            result = cal.transformaPolar(x, y);
            textRaio.setText(String.valueOf(new DecimalFormat("#.00").format(result[0])));
            textAngulo.setText(String.valueOf(new DecimalFormat("#.00").format(result[1])));
            r = result[0];
            ang = result[1];
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_textXFocusLost

    private void textRaioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textRaioFocusLost

        try {
            r = verificaDouble(textRaio.getText().replaceAll(",", "."));
            if (textAngulo.getText().isEmpty()) {
                textAngulo.setText("0");
            }

            ang = verificaDouble(textAngulo.getText().replaceAll(",", "."));

            result = cal.transformaCartesiano(r, ang);
            textX.setText(String.valueOf(new DecimalFormat("#.00").format(result[0])));
            textY.setText(String.valueOf(new DecimalFormat("#.00").format(result[1])));

            x = result[0];
            y = result[1];
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_textRaioFocusLost

    public Double verificaDouble(String a) throws Exception {
        try {
            return Double.parseDouble(a);
        } catch (Exception e) {
            throw new Exception("Número inválido.");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botaoCartesiana;
    private javax.swing.JButton botaoInserir;
    private javax.swing.JRadioButton botaoPolar;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelAngulo;
    private javax.swing.JLabel labelDirecao;
    private javax.swing.JLabel labelRaio;
    private javax.swing.JLabel labelVelocidade;
    private javax.swing.JLabel labelX;
    private javax.swing.JLabel labelY;
    private javax.swing.JTextField textAngulo;
    private javax.swing.JTextField textDirecao;
    private javax.swing.JTextField textRaio;
    private javax.swing.JTextField textVelocidade;
    private javax.swing.JTextField textX;
    private javax.swing.JTextField textY;
    // End of variables declaration//GEN-END:variables
}
