/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.Calc;
import Classes.Get_Set_Pontos;
import Classes.Insert;
import java.awt.Graphics;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author comp9
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    boolean alive = true, acaoExclusao = false;
    Queue<Get_Set_Pontos> filaAcao = new LinkedList<>();
    Queue<Get_Set_Pontos> filaCalculo = new LinkedList<>();
    DefaultTableModel modelo = new DefaultTableModel();
    EntradaDados enterdate;
    Calc cal = new Calc();
    Ajuda ajuda = new Ajuda();
    double x, y, r, ang, vel, dir;
    double[] result = new double[2];
    private final Insert t = new Insert(this);
    Graphics graph;
    ArrayList<Get_Set_Pontos> arrayPontos;

    public TelaPrincipal() {

        initComponents();

        graph = painelRadar.getGraphics();
        modelo = (DefaultTableModel) tabelaDatagrid.getModel();

        enterdate = new EntradaDados(modelo, this);
        textoRelatorio.setLineWrap(true);

    }

    public Queue<Get_Set_Pontos> getFilaAcao() {
        return filaAcao;
    }

    public DefaultTableModel getModel() {
        return modelo;
    }

    public void setAcaoExclusao(boolean acaoExclusao) {
        this.acaoExclusao = acaoExclusao;
    }

    public void insereTabela(Object data[]) {
        modelo.addRow(data);
    }

    public JPanel getPainelRadar() {
        return painelRadar;
    }

    public boolean isAcaoExclusao() {
        return acaoExclusao;
    }

    public boolean isAlive() {
        return alive;
    }

    public void setarCampos() {

        textAngulo.setText("");
        textDirecao.setText("");
        textRaio.setText("");
        textVelocidade.setText("");
        textX.setText("");
        textY.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        painelDesktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        painelRadar = new javax.swing.JPanel();
        painelDatagrid = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaDatagrid = new javax.swing.JTable();
        abasPainel = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoRelatorio = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        botaoInserir = new javax.swing.JButton();
        textAngulo = new javax.swing.JTextField();
        textRaio = new javax.swing.JTextField();
        botaoPolar = new javax.swing.JRadioButton();
        textX = new javax.swing.JTextField();
        textY = new javax.swing.JTextField();
        labelY = new javax.swing.JLabel();
        labelX = new javax.swing.JLabel();
        botaoCartesiana = new javax.swing.JRadioButton();
        labelRaio = new javax.swing.JLabel();
        labelAngulo = new javax.swing.JLabel();
        labelDirecao = new javax.swing.JLabel();
        labelVelocidade = new javax.swing.JLabel();
        textVelocidade = new javax.swing.JTextField();
        textDirecao = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textXescalar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textYescalar = new javax.swing.JTextField();
        botaoEscalar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        textAngulorotacionar = new javax.swing.JTextField();
        botaoRotacionar = new javax.swing.JButton();
        textXrotacionar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textYrotacionar = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        textXtransladar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textYtransladar = new javax.swing.JTextField();
        botaoTransladar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botãoProxAeroporto = new javax.swing.JButton();
        botãoProxEntreSi = new javax.swing.JButton();
        botãoRotaColisao = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        menuAjuda = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Selecionar", "Nome", "X", "Y", "r", "Ângulo", "Velocidade", "Direção"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelRadar.setBorder(javax.swing.BorderFactory.createTitledBorder("Radar"));
        painelRadar.setToolTipText("");
        painelRadar.setName(""); // NOI18N

        javax.swing.GroupLayout painelRadarLayout = new javax.swing.GroupLayout(painelRadar);
        painelRadar.setLayout(painelRadarLayout);
        painelRadarLayout.setHorizontalGroup(
            painelRadarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        painelRadarLayout.setVerticalGroup(
            painelRadarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        painelDatagrid.setBorder(javax.swing.BorderFactory.createTitledBorder("Datagrid"));

        tabelaDatagrid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Select", "Nome", "X", "Y", "r", "Ângulo", "Velocidade", "Direção"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaDatagrid);
        if (tabelaDatagrid.getColumnModel().getColumnCount() > 0) {
            tabelaDatagrid.getColumnModel().getColumn(0).setResizable(false);
            tabelaDatagrid.getColumnModel().getColumn(0).setPreferredWidth(15);
        }
        tabelaDatagrid.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout painelDatagridLayout = new javax.swing.GroupLayout(painelDatagrid);
        painelDatagrid.setLayout(painelDatagridLayout);
        painelDatagridLayout.setHorizontalGroup(
            painelDatagridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDatagridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelDatagridLayout.setVerticalGroup(
            painelDatagridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        );

        textoRelatorio.setEditable(false);
        textoRelatorio.setColumns(20);
        textoRelatorio.setRows(5);
        jScrollPane3.setViewportView(textoRelatorio);

        abasPainel.addTab("Relatório", jScrollPane3);

        botaoInserir.setText("Inserir");
        botaoInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInserirbotaoInserirActionPerformed(evt);
            }
        });

        textAngulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textAngulotextAnguloFocusLost(evt);
            }
        });

        textRaio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textRaiotextRaioFocusLost(evt);
            }
        });

        buttonGroup1.add(botaoPolar);
        botaoPolar.setText("Polar");
        botaoPolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPolarbotaoPolarActionPerformed(evt);
            }
        });

        textX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textXtextXFocusLost(evt);
            }
        });
        textX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textXtextXMouseExited(evt);
            }
        });
        textX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textXActionPerformed(evt);
            }
        });

        textY.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textYtextYFocusLost(evt);
            }
        });

        labelY.setText("Y:");

        labelX.setText("X:");

        buttonGroup1.add(botaoCartesiana);
        botaoCartesiana.setText("Cartesiana");
        botaoCartesiana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCartesianabotaoCartesiana2ActionPerformed(evt);
            }
        });

        labelRaio.setText("Raio:");

        labelAngulo.setText("Ângulo:");

        labelDirecao.setText("Direção:");

        labelVelocidade.setText("Velocidade:");

        textDirecao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textDirecaotextDirecaoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(labelY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textY))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(labelX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textX, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelAngulo)
                            .addComponent(labelRaio)))
                    .addComponent(botaoCartesiana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(botaoPolar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textAngulo, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(textRaio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelVelocidade)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(labelDirecao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textDirecao, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(textVelocidade))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(botaoInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPolar)
                    .addComponent(botaoCartesiana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelX)
                            .addComponent(textX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRaio)
                            .addComponent(textRaio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelY)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelAngulo)
                                .addComponent(textAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelVelocidade)
                            .addComponent(textVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textDirecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDirecao))))
                .addGap(29, 29, 29)
                .addComponent(botaoInserir)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        abasPainel.addTab("Entrada de Dados", jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Escalar"));

        jLabel6.setText("X:");

        jLabel7.setText("Y:");

        textYescalar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textYescalarFocusLost(evt);
            }
        });

        botaoEscalar.setText("OK");
        botaoEscalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEscalarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textXescalar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textYescalar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(botaoEscalar))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(textYescalar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(textXescalar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoEscalar))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Rotacionar"));

        jLabel8.setText("Ângulo:");

        textAngulorotacionar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textAngulorotacionarFocusLost(evt);
            }
        });

        botaoRotacionar.setText("OK");
        botaoRotacionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRotacionarActionPerformed(evt);
            }
        });

        jLabel11.setText("X:");

        jLabel12.setText("Y:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textAngulorotacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textXrotacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textYrotacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(botaoRotacionar))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(textYrotacionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(textXrotacionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(textAngulorotacionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoRotacionar))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Transladar"));

        jLabel9.setText("X:");

        jLabel10.setText("Y:");

        textYtransladar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textYtransladarFocusLost(evt);
            }
        });

        botaoTransladar.setText("OK");
        botaoTransladar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTransladarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textXtransladar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textYtransladar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoTransladar))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textYtransladar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(textXtransladar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoTransladar))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        abasPainel.addTab("Transformar", jPanel2);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel.png"))); // NOI18N
        jLabel1.setText(".");

        jLabel2.setFont(new java.awt.Font("Haettenschweiler", 0, 80)); // NOI18N
        jLabel2.setText("SAFE");

        botãoProxAeroporto.setText("Aviões próximos ao Aeroporto");
        botãoProxAeroporto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoProxAeroportoActionPerformed(evt);
            }
        });

        botãoProxEntreSi.setText("Aviões Próximos entre Sí");
        botãoProxEntreSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoProxEntreSiActionPerformed(evt);
            }
        });

        botãoRotaColisao.setText("Aviões em Rota de Colisão");
        botãoRotaColisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoRotaColisaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botãoProxAeroporto)
                            .addComponent(botãoProxEntreSi, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botãoRotaColisao, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(abasPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(painelRadar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(painelDatagrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botãoProxAeroporto)
                                        .addGap(7, 7, 7)
                                        .addComponent(botãoProxEntreSi)
                                        .addGap(7, 7, 7)
                                        .addComponent(botãoRotaColisao)))))
                        .addGap(24, 24, 24)
                        .addComponent(abasPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(painelRadar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(painelDatagrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelRadar.getAccessibleContext().setAccessibleName("");

        painelDesktop.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelDesktopLayout = new javax.swing.GroupLayout(painelDesktop);
        painelDesktop.setLayout(painelDesktopLayout);
        painelDesktopLayout.setHorizontalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        painelDesktopLayout.setVerticalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDesktopLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuAjuda.setText("Ajuda");
        menuAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAjudaMouseClicked(evt);
            }
        });
        barraMenu.add(menuAjuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAjudaMouseClicked

        painelDesktop.add(ajuda);
        ajuda.setVisible(true);
        ajuda.setPosicao();

    }//GEN-LAST:event_menuAjudaMouseClicked

    private void textDirecaotextDirecaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDirecaotextDirecaoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_textDirecaotextDirecaoFocusLost

    private void botaoCartesianabotaoCartesiana2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCartesianabotaoCartesiana2ActionPerformed

        textX.setEnabled(true);
        textY.setEnabled(true);
        textRaio.setEnabled(false);
        textAngulo.setEnabled(false);

    }//GEN-LAST:event_botaoCartesianabotaoCartesiana2ActionPerformed

    private void textYtextYFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textYtextYFocusLost

        try {
            if (textX.getText().isEmpty()) {
                textX.setText("0");
            }
            x = verificaDouble(textX.getText().replaceAll(",", "."));
            y = verificaDouble(textY.getText().replaceAll(",", "."));

            result = cal.transformaPolar(x, y);
            textRaio.setText(String.valueOf(new DecimalFormat("#.00").format(result[0])));
            textAngulo.setText(String.valueOf(new DecimalFormat("#.00").format(result[1])));
            r = result[0];
            ang = result[1];
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_textYtextYFocusLost

    private void textXtextXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textXtextXMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_textXtextXMouseExited

    private void textXtextXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textXtextXFocusLost

        try {
            x = verificaDouble(textX.getText().replaceAll(",", "."));

            if (textY.getText().isEmpty()) {
                textY.setText("0");
            }
            y = verificaDouble(textY.getText().replaceAll(",", "."));

            result = cal.transformaPolar(x, y);
            textRaio.setText(String.valueOf(new DecimalFormat("#.00").format(result[0])));
            textAngulo.setText(String.valueOf(new DecimalFormat("#.00").format(result[1])));
            r = result[0];
            ang = result[1];
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_textXtextXFocusLost

    private void botaoPolarbotaoPolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPolarbotaoPolarActionPerformed

        textX.setEnabled(false);
        textY.setEnabled(false);
        textRaio.setEnabled(true);
        textAngulo.setEnabled(true);

    }//GEN-LAST:event_botaoPolarbotaoPolarActionPerformed

    private void textRaiotextRaioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textRaiotextRaioFocusLost

        try {
            r = verificaDouble(textRaio.getText().replaceAll(",", "."));
            if (textAngulo.getText().isEmpty()) {
                textAngulo.setText("0");
            }

            ang = verificaDouble(textAngulo.getText().replaceAll(",", "."));

            result = cal.transformaCartesiano(r, ang);
            textX.setText(String.valueOf(new DecimalFormat("#.00").format(result[0])));
            textY.setText(String.valueOf(new DecimalFormat("#.00").format(result[1])));

            x = result[0];
            y = result[1];
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_textRaiotextRaioFocusLost

    private void textAngulotextAnguloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textAngulotextAnguloFocusLost

        try {

            if (textRaio.getText().isEmpty()) {
                textRaio.setText("0");
            }

            r = verificaDouble(textRaio.getText().replaceAll(",", "."));
            ang = verificaDouble(textAngulo.getText().replaceAll(",", "."));

            result = cal.transformaCartesiano(r, ang);
            textX.setText(String.valueOf(new DecimalFormat("#.00").format(result[0])));
            textY.setText(String.valueOf(new DecimalFormat("#.00").format(result[1])));

            x = result[0];
            y = result[1];
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_textAngulotextAnguloFocusLost

    private void botaoInserirbotaoInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInserirbotaoInserirActionPerformed

        try {
            vel = verificaDouble(textVelocidade.getText().replaceAll(",", "."));
            dir = verificaDouble(textDirecao.getText().replaceAll(",", "."));
            Object data[] = new Object[]{false, modelo.getRowCount(),
                String.valueOf(new DecimalFormat("#.00").format(x)), String.valueOf(new DecimalFormat("#.00").format(y)),
                String.valueOf(new DecimalFormat("#.00").format(r)), String.valueOf(new DecimalFormat("#.00").format(ang)),
                String.valueOf(new DecimalFormat("#.00").format(vel)), String.valueOf(new DecimalFormat("#.00").format(dir))};
            //System.out.println("" + model.getRowCount());
            insereTabela(data);
            t.run();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
        }

        setarCampos();

    }//GEN-LAST:event_botaoInserirbotaoInserirActionPerformed

    private void textXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textXActionPerformed

    private void textYescalarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textYescalarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_textYescalarFocusLost

    private void botaoEscalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEscalarActionPerformed
        // TODO add your handling code here:
        try {
            buscarSelecao();
            double Sx = verificaDouble(textXescalar.getText().replaceAll(",", "."));
            double Sy = verificaDouble(textYescalar.getText().replaceAll(",", "."));

            for (Get_Set_Pontos p : filaCalculo) {
                result = cal.calculaEscala(p.getX(), p.getY(), Sx, Sy);
                insereValorFormatado(result[0], p.getLinha(), 2);
                insereValorFormatado(result[1], p.getLinha(), 3);
                result = cal.transformaPolar(result[0], result[1]);
                insereValorFormatado(result[0], p.getLinha(), 4);
                insereValorFormatado(result[1], p.getLinha(), 5);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
        }

        t.run();
    }//GEN-LAST:event_botaoEscalarActionPerformed

    private void botaoRotacionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRotacionarActionPerformed
        // TODO add your handling code here:
        try {
            buscarSelecao();
            double ang = verificaDouble(textAngulorotacionar.getText().replaceAll(",", "."));
            double xR = verificaDouble(textXrotacionar.getText().replaceAll(",", "."));
            double yR = verificaDouble(textYrotacionar.getText().replaceAll(",", "."));

            for (Get_Set_Pontos p : filaCalculo) {
                result = cal.calculaRotacao(p.getX(), p.getY(), ang, xR, yR);
                insereValorFormatado(result[0], p.getLinha(), 2);
                insereValorFormatado(result[1], p.getLinha(), 3);
                result = cal.transformaPolar(result[0], result[1]);
                insereValorFormatado(result[0], p.getLinha(), 4);
                insereValorFormatado(result[1], p.getLinha(), 5);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
        }

        t.run();
    }//GEN-LAST:event_botaoRotacionarActionPerformed

    private void textYtransladarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textYtransladarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_textYtransladarFocusLost

    private void botaoTransladarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTransladarActionPerformed
        // TODO add your handling code here:
        try {
            buscarSelecao();
            double Tx = verificaDouble(textXtransladar.getText().replaceAll(",", "."));
            double Ty = verificaDouble(textYtransladar.getText().replaceAll(",", "."));

            for (Get_Set_Pontos p : filaCalculo) {
                result = cal.calculaTranslacao(p.getX(), p.getY(), Tx, Ty);
                insereValorFormatado(result[0], p.getLinha(), 2);
                insereValorFormatado(result[1], p.getLinha(), 3);
                result = cal.transformaPolar(result[0], result[1]);
                insereValorFormatado(result[0], p.getLinha(), 4);
                insereValorFormatado(result[1], p.getLinha(), 5);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
        }

        t.run();
    }//GEN-LAST:event_botaoTransladarActionPerformed

    private void textAngulorotacionarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textAngulorotacionarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_textAngulorotacionarFocusLost

    private void botãoProxEntreSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoProxEntreSiActionPerformed

        buscarTodos();
        String str = "", str2 = "";
        Get_Set_Pontos p1, p2;
        double dist;

        for (int i = 0; i < arrayPontos.size() - 1; i++) {
            p1 = arrayPontos.get(i);
            str2 = "Avião " + p1.getNome() + ":\n";
            for (int j = i + 1; j < arrayPontos.size(); j++) {
                p2 = arrayPontos.get(j);
                dist = cal.calculaDistanciaDoisPontos(p1.getX(), p1.getY(), p2.getX(), p2.getY());
                str2 += p2.getNome() + " - " + dist + " Km\n";

            }
            str += str2;
        }

        textoRelatorio.setText("Distância entre os aviões:\n" + str);

        abasPainel.setSelectedIndex(0);


    }//GEN-LAST:event_botãoProxEntreSiActionPerformed

    private void botãoRotaColisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoRotaColisaoActionPerformed

        double par = Double.parseDouble(JOptionPane.showInputDialog(null, "Informe o tempo mínimo: ", "Informe", JOptionPane.QUESTION_MESSAGE).replaceAll(",", "."));
        
        buscarTodos();
        String str = "", str2 = "";
        Get_Set_Pontos p1, p2;
        double t1,t2, dif;

        for (int i = 0; i < arrayPontos.size() - 1; i++) {
            p1 = arrayPontos.get(i);
            str2 = p1.getNome() + ":\n";
            for (int j = i + 1; j < arrayPontos.size(); j++) {
                p2 = arrayPontos.get(j);
                
                result = cal.calculaInterseccao(p1.getX(), p1.getY(), p1.getDir(), p2.getX(), p2.getY(), p2.getDir());
                
                
                if(result == null){
                    str2 += p2.getNome() + " - Não se cruzam.\n";
                }else{
                    t1 = cal.calculaTempo(p1.getX(), p1.getY(), p1.getVel(), result[0], result[1]);
                    t2 = cal.calculaTempo(p2.getX(), p2.getY(), p2.getVel(), result[0], result[1]);
                    
                    dif = t1-t2;
                    
                    System.out.println(t1);
                    System.out.println(t2);
                    System.out.println(dif);
                    if(Math.abs(dif)<par){
                        str2 += p2.getNome() + " - Vão passar pelo mesmo ponto com intervalo de "+Math.abs(dif)+"s.\n";
                    }
                }

            }
            str += str2;
        }
        
        textoRelatorio.setText("" + str);
        
        JOptionPane.showMessageDialog(null, str, "Relatório", JOptionPane.INFORMATION_MESSAGE);
         
    }//GEN-LAST:event_botãoRotaColisaoActionPerformed

    private void botãoProxAeroportoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoProxAeroportoActionPerformed

        double valorDist = Double.parseDouble(JOptionPane.showInputDialog(null, "Informe a distância em Km", "Informe", JOptionPane.QUESTION_MESSAGE).replaceAll(",", "."));
        buscarTodos();

        String str = "";
        for (Get_Set_Pontos p : arrayPontos) {
            if (p.getR() < valorDist) {
                str += p.getNome() + " - " + p.getR() + " km\n";
            }
        }

        if (str.isEmpty()) {
            textoRelatorio.setText("Não existem aviões próximos ao aeroporto na distância mínima indicada!");
        } else {

            textoRelatorio.setText("Os aviões abaixo estão próximos do aeroporto:\n" + str);
        }

        abasPainel.setSelectedIndex(0);


    }//GEN-LAST:event_botãoProxAeroportoActionPerformed

    public Double verificaDouble(String a) throws Exception {
        try {
            return Double.parseDouble(a);
        } catch (Exception e) {
            throw new Exception("Número inválido.");
        }

    }

    public void buscarTodos() {
        Get_Set_Pontos ponto;
        arrayPontos = new ArrayList<>();
        for (int i = 0; i < modelo.getRowCount(); i++) {

            ponto = new Get_Set_Pontos();
            ponto.setLinha(i);
            ponto.setX(Double.parseDouble(modelo.getValueAt(i, 2).toString().replace(",", ".")));
            ponto.setY(Double.parseDouble(modelo.getValueAt(i, 3).toString().replace(",", ".")));
            ponto.setR(Double.parseDouble(modelo.getValueAt(i, 4).toString().replace(",", ".")));
            ponto.setAng(Double.parseDouble(modelo.getValueAt(i, 5).toString().replace(",", ".")));
            ponto.setVel(Double.parseDouble(modelo.getValueAt(i, 6).toString().replace(",", ".")));
            ponto.setDir(Double.parseDouble(modelo.getValueAt(i, 7).toString().replace(",", ".")));
            ponto.setNome(modelo.getValueAt(i, 1).toString());

            arrayPontos.add(ponto);
        }
    }

    public void buscarSelecao() { //se tiver caixa seleciona armazenada nas filas de Ação e Calculo
        Get_Set_Pontos ponto;
        for (int i = 0; i < modelo.getRowCount(); i++) {
            if ((Boolean) modelo.getValueAt(i, 0)) {
                ponto = new Get_Set_Pontos();
                ponto.setLinha(i);
                ponto.setX(Double.parseDouble(modelo.getValueAt(i, 2).toString().replace(",", ".")));
                ponto.setY(Double.parseDouble(modelo.getValueAt(i, 3).toString().replace(",", ".")));

                filaAcao.add(ponto);
                filaCalculo.add(ponto);

            }
        }
        if (!filaAcao.isEmpty()) {
            acaoExclusao = true;
        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma linha selecionada.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }

    }

    public void insereValorFormatado(double valor, int row, int column) {
        String vForm = String.valueOf(new DecimalFormat("#.00").format(valor));
        modelo.setValueAt(vForm, row, column);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abasPainel;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JRadioButton botaoCartesiana;
    private javax.swing.JButton botaoEscalar;
    private javax.swing.JButton botaoInserir;
    private javax.swing.JRadioButton botaoPolar;
    private javax.swing.JButton botaoRotacionar;
    private javax.swing.JButton botaoTransladar;
    private javax.swing.JButton botãoProxAeroporto;
    private javax.swing.JButton botãoProxEntreSi;
    private javax.swing.JButton botãoRotaColisao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelAngulo;
    private javax.swing.JLabel labelDirecao;
    private javax.swing.JLabel labelRaio;
    private javax.swing.JLabel labelVelocidade;
    private javax.swing.JLabel labelX;
    private javax.swing.JLabel labelY;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JPanel painelDatagrid;
    private javax.swing.JDesktopPane painelDesktop;
    private javax.swing.JPanel painelRadar;
    private javax.swing.JTable tabelaDatagrid;
    private javax.swing.JTextField textAngulo;
    private javax.swing.JTextField textAngulorotacionar;
    private javax.swing.JTextField textDirecao;
    private javax.swing.JTextField textRaio;
    private javax.swing.JTextField textVelocidade;
    private javax.swing.JTextField textX;
    private javax.swing.JTextField textXescalar;
    private javax.swing.JTextField textXrotacionar;
    private javax.swing.JTextField textXtransladar;
    private javax.swing.JTextField textY;
    private javax.swing.JTextField textYescalar;
    private javax.swing.JTextField textYrotacionar;
    private javax.swing.JTextField textYtransladar;
    private javax.swing.JTextArea textoRelatorio;
    // End of variables declaration//GEN-END:variables
}
